server:
  port: 8082

spring:
  application:
    name: eduflex-scorm
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/eduflex_scorm}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

minio:
  url: ${MINIO_URL:http://localhost:9009}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  bucket: ${MINIO_BUCKET:eduflex-storage}

eduflex:
  core:
    url: ${CORE_URL:http://localhost:8080}
