package com.eduflex.backend.repository;

import com.eduflex.backend.model.Invoice;
import com.eduflex.backend.model.User;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

@Repository
public interface InvoiceRepository extends JpaRepository<Invoice, Long> {

    Optional<Invoice> findByInvoiceNumber(String invoiceNumber);

    List<Invoice> findByUser(User user);

    List<Invoice> findByUserOrderByIssueDateDesc(User user);

    List<Invoice> findByStatus(Invoice.InvoiceStatus status);

    List<Invoice> findByStatusAndDueDateBefore(Invoice.InvoiceStatus status, LocalDate date);

    List<Invoice> findByAutoGeneratedTrue();

    long countByUser(User user);
}
