export const COURSE_CATEGORIES = [
    "Affärsutveckling och ledarskap",
    "Artificiell intelligens",
    "Barn och fritid",
    "Beteende- och samhällsvetenskap",
    "Butik, administration och personal",
    "Bygg och anläggning",
    "CAD",
    "Data/IT",
    "Ekonomi, administration och försäljning",
    "El och energi",
    "Fotografisk bild",
    "Förberedande och orienterande",
    "Hotell och turism",
    "Hälso- och sjukvård samt socialt arbete",
    "Inköp och logistik",
    "Journalistik och information",
    "Juridik",
    "Kombinationsutbildning",
    "Komvuxarbete",
    "Lantbruk, djurvård, trädgård",
    "Marknadsföring",
    "Matematik och naturvetenskap",
    "Media och kommunikation",
    "Måleri",
    "Samhällsbyggnad och byggteknik",
    "SFI",
    "Sjöfart",
    "Språk",
    "Teknik och tillverkning",
    "Transporttjänster",
    "Vård och omsorg",
    "Övrigt"
];
