CREATE TABLE IF NOT EXISTS education_programs (
    id bigint generated by default as identity,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE,
    description TEXT,
    category VARCHAR(255),
    sun_code VARCHAR(50),
    is_open BOOLEAN DEFAULT TRUE,
    requires_lia BOOLEAN DEFAULT FALSE,
    total_credits INT,
    job_tech_skills TEXT,
    primary key (id)
);

CREATE TABLE IF NOT EXISTS program_courses (
    program_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    PRIMARY KEY (program_id, course_id),
    CONSTRAINT fk_program FOREIGN KEY (program_id) REFERENCES education_programs(id) ON DELETE CASCADE,
    CONSTRAINT fk_course FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS program_applications (
    id bigint generated by default as identity,
    user_id BIGINT NOT NULL,
    program_id BIGINT NOT NULL,
    status VARCHAR(50) DEFAULT 'PENDING',
    admin_note TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    primary key (id),
    CONSTRAINT fk_app_user FOREIGN KEY (user_id) REFERENCES app_users(id) ON DELETE CASCADE,
    CONSTRAINT fk_app_program FOREIGN KEY (program_id) REFERENCES education_programs(id) ON DELETE CASCADE
);
