-- Add package_id to scorm_packages
ALTER TABLE scorm_packages ADD COLUMN IF NOT EXISTS package_id VARCHAR(255);

-- Create cmi5_packages if missing (safeguard)
CREATE TABLE IF NOT EXISTS cmi5_packages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT,
    package_id VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    launch_url VARCHAR(255) NOT NULL,
    registration VARCHAR(255) NOT NULL,
    uploaded_at TIMESTAMP,
    size_bytes BIGINT NOT NULL,
    CONSTRAINT FK_cmi5_course FOREIGN KEY (course_id) REFERENCES courses(id)
);

-- Add package_id to cmi5_packages if table existed but column was missing
DO $$ 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name='cmi5_packages' 
                     AND column_name='package_id' 
                     AND table_schema = current_schema()) THEN
        ALTER TABLE cmi5_packages ADD COLUMN package_id VARCHAR(255);
    END IF;
END $$;
