-- Academic Governance for Rektorspaket
CREATE TABLE IF NOT EXISTS academic_terms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    is_locked BOOLEAN DEFAULT FALSE,
    academic_year VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS school_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    version VARCHAR(255),
    requires_acceptance BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Table for tracking policy acceptance
CREATE TABLE IF NOT EXISTS policy_acceptances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_id BIGINT REFERENCES school_policies(id),
    user_id BIGINT REFERENCES app_users(id),
    accepted_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(policy_id, user_id)
);

-- Index för snabbare sökning
CREATE INDEX IF NOT EXISTS idx_terms_dates ON academic_terms(start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_policy_acceptances_user ON policy_acceptances(user_id);
