-- Quality & Safety for Rektorspaket
CREATE TABLE IF NOT EXISTS incident_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    status VARCHAR(50) DEFAULT 'REPORTED',
    type VARCHAR(50) DEFAULT 'OTHER',
    reporter_id BIGINT REFERENCES app_users(id),
    involved_student_id BIGINT REFERENCES app_users(id),
    investigation_notes TEXT,
    actions_taken TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS staff_observations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    observer_id BIGINT NOT NULL REFERENCES app_users(id),
    observed_teacher_id BIGINT NOT NULL REFERENCES app_users(id),
    notes TEXT NOT NULL,
    observed_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Index för snabbare sökning
CREATE INDEX IF NOT EXISTS idx_incident_status ON incident_reports(status);
CREATE INDEX IF NOT EXISTS idx_incident_student ON incident_reports(involved_student_id);
CREATE INDEX IF NOT EXISTS idx_observations_teacher ON staff_observations(observed_teacher_id);
