-- Add Holidays table
CREATE TABLE IF NOT EXISTS holidays (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    assignments_allowed BOOLEAN DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_holidays_dates ON holidays(start_date, end_date);
