-- Systematiskt Kvalitetsarbete (SKA) 2.0 Engine
CREATE TABLE IF NOT EXISTS quality_goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    owner_id BIGINT REFERENCES app_users(id),
    status VARCHAR(50) DEFAULT 'ACTIVE', -- ACTIVE, ARCHIVED
    target_date DATE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS quality_indicators (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goal_id BIGINT NOT NULL REFERENCES quality_goals(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    indicator_type VARCHAR(50) NOT NULL, -- ATTENDANCE, GRADES, INCIDENTS, SURVEY, MANUAL
    target_value DOUBLE PRECISION,
    current_value DOUBLE PRECISION DEFAULT 0.0,
    unit VARCHAR(20), -- %, count, index
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS quality_checkpoints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    scheduled_date DATE NOT NULL,
    term_id BIGINT REFERENCES academic_terms(id),
    is_completed BOOLEAN DEFAULT FALSE,
    completion_notes TEXT,
    completed_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Index för prestanda
CREATE INDEX IF NOT EXISTS idx_quality_goals_owner ON quality_goals(owner_id);
CREATE INDEX IF NOT EXISTS idx_quality_indicators_goal ON quality_indicators(goal_id);
CREATE INDEX IF NOT EXISTS idx_quality_checkpoints_date ON quality_checkpoints(scheduled_date);
