-- Migration to support AI-generated Management Reports with Archiving
CREATE TABLE IF NOT EXISTS management_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    period VARCHAR(50),
    content TEXT NOT NULL, -- The AI generated markdown
    data_snapshot JSONB,    -- Snapshot of raw metrics (attendance, grades, risks, etc.)
    author_id BIGINT REFERENCES app_users(id),
    status VARCHAR(20) DEFAULT 'DRAFT', -- DRAFT, FINAL
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_management_reports_author ON management_reports(author_id);
CREATE INDEX IF NOT EXISTS idx_management_reports_created ON management_reports(created_at);
