-- 1. Create adaptive_recommendations if missing (especially for tenant schemas)
CREATE TABLE IF NOT EXISTS adaptive_recommendations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    type VARCHAR(50) NOT NULL,
    ai_reasoning TEXT,
    status VARCHAR(50) DEFAULT 'NEW',
    priority_score INTEGER DEFAULT 50,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_rec_user FOREIGN KEY (user_id) REFERENCES app_users(id)
);

-- 2. Add reasoning_trace if missing
ALTER TABLE adaptive_recommendations ADD COLUMN IF NOT EXISTS reasoning_trace TEXT;
