-- Final creation of ai_audit_logs with IF NOT EXISTS for tenant safety
CREATE TABLE IF NOT EXISTS ai_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    action_type VARCHAR(100) NOT NULL,
    model_used VARCHAR(100),
    prompt_hash VARCHAR(64),
    input_context TEXT,
    output_result TEXT,
    reasoning_trace TEXT,
    audit_metadata TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Idempotent index creation
CREATE INDEX IF NOT EXISTS idx_ai_audit_user_id ON ai_audit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_ai_audit_created_at ON ai_audit_logs(created_at);
