-- Comprehensive migration: Add ALL missing columns/tables that exist in JPA entities but not in the database

-- 1. audit_logs: missing change_data
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS change_data TEXT;

-- 2. documents: missing category, official, is_global
ALTER TABLE documents ADD COLUMN IF NOT EXISTS category VARCHAR(255) DEFAULT 'GENERAL';
ALTER TABLE documents ADD COLUMN IF NOT EXISTS official BOOLEAN DEFAULT false;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS is_global BOOLEAN DEFAULT false;

-- 3. message_folders: entire table missing
CREATE TABLE IF NOT EXISTS message_folders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255),
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_message_folders_user FOREIGN KEY (user_id) REFERENCES app_users(id)
);

-- 4. messages: missing folder_id and parent_id
ALTER TABLE messages ADD COLUMN IF NOT EXISTS folder_id BIGINT;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS parent_id BIGINT;
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_messages_folder') THEN
        ALTER TABLE messages ADD CONSTRAINT fk_messages_folder FOREIGN KEY (folder_id) REFERENCES message_folders(id);
    END IF;
END $$;

-- 5. adaptive_recommendations: missing content_url and associated_course_id
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'adaptive_recommendations') THEN
        ALTER TABLE adaptive_recommendations ADD COLUMN IF NOT EXISTS content_url VARCHAR(255);
        ALTER TABLE adaptive_recommendations ADD COLUMN IF NOT EXISTS associated_course_id BIGINT;
    END IF;
END $$;
