-- Comprehensive migration: Create ALL missing tables that exist as JPA entities but not in the database

-- 1. achievements
CREATE TABLE IF NOT EXISTS achievements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    icon_url VARCHAR(255),
    tier VARCHAR(255),
    category VARCHAR(255),
    xp_reward INTEGER DEFAULT 0,
    unlock_criteria TEXT,
    is_active BOOLEAN DEFAULT true,
    organization_id BIGINT,
    created_at TIMESTAMP
);

-- 2. user_achievements
CREATE TABLE IF NOT EXISTS user_achievements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    achievement_id BIGINT NOT NULL,
    progress INTEGER DEFAULT 0,
    unlocked BOOLEAN DEFAULT false,
    unlocked_at TIMESTAMP,
    created_at TIMESTAMP,
    CONSTRAINT fk_user_achievements_user FOREIGN KEY (user_id) REFERENCES app_users(id),
    CONSTRAINT fk_user_achievements_achievement FOREIGN KEY (achievement_id) REFERENCES achievements(id)
);

-- 3. daily_challenges
CREATE TABLE IF NOT EXISTS daily_challenges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    challenge_type VARCHAR(255),
    title VARCHAR(255),
    description VARCHAR(255),
    target_value INTEGER DEFAULT 0,
    current_progress INTEGER DEFAULT 0,
    xp_reward INTEGER DEFAULT 0,
    completed BOOLEAN DEFAULT false,
    challenge_date TIMESTAMP,
    completed_at TIMESTAMP,
    created_at TIMESTAMP,
    CONSTRAINT fk_daily_challenges_user FOREIGN KEY (user_id) REFERENCES app_users(id)
);

-- 4. user_streaks
CREATE TABLE IF NOT EXISTS user_streaks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    streak_type VARCHAR(255),
    current_streak INTEGER DEFAULT 0,
    longest_streak INTEGER DEFAULT 0,
    last_activity_date DATE,
    freezes_available INTEGER DEFAULT 0,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_user_streaks_user FOREIGN KEY (user_id) REFERENCES app_users(id)
);

-- 5. edugame_quests
CREATE TABLE IF NOT EXISTS edugame_quests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(255),
    description VARCHAR(500),
    type VARCHAR(255),
    target_count INTEGER DEFAULT 0,
    current_count INTEGER DEFAULT 0,
    reward_xp INTEGER DEFAULT 0,
    is_completed BOOLEAN DEFAULT false,
    expires_at DATE,
    CONSTRAINT fk_edugame_quests_user FOREIGN KEY (user_id) REFERENCES app_users(id)
);

-- 6. edugame_friendships
CREATE TABLE IF NOT EXISTS edugame_friendships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id BIGINT NOT NULL,
    receiver_id BIGINT NOT NULL,
    status VARCHAR(255),
    created_at TIMESTAMP,
    CONSTRAINT fk_friendships_requester FOREIGN KEY (requester_id) REFERENCES app_users(id),
    CONSTRAINT fk_friendships_receiver FOREIGN KEY (receiver_id) REFERENCES app_users(id)
);

-- 7. edugame_social_streaks
CREATE TABLE IF NOT EXISTS edugame_social_streaks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user1_id BIGINT NOT NULL,
    user2_id BIGINT NOT NULL,
    current_streak INTEGER DEFAULT 0,
    longest_streak INTEGER DEFAULT 0,
    last_activity_date DATE,
    CONSTRAINT fk_social_streaks_user1 FOREIGN KEY (user1_id) REFERENCES app_users(id),
    CONSTRAINT fk_social_streaks_user2 FOREIGN KEY (user2_id) REFERENCES app_users(id)
);

-- 8. social_comments
CREATE TABLE IF NOT EXISTS social_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT,
    author_id BIGINT,
    target_id VARCHAR(255),
    target_type VARCHAR(255),
    parent_id BIGINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_social_comments_author FOREIGN KEY (author_id) REFERENCES app_users(id),
    CONSTRAINT fk_social_comments_parent FOREIGN KEY (parent_id) REFERENCES social_comments(id)
);

-- 9. social_comment_likes (join table for Comment likes)
CREATE TABLE IF NOT EXISTS social_comment_likes (
    comment_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (comment_id, user_id),
    CONSTRAINT fk_comment_likes_comment FOREIGN KEY (comment_id) REFERENCES social_comments(id),
    CONSTRAINT fk_comment_likes_user FOREIGN KEY (user_id) REFERENCES app_users(id)
);

-- 10. eduai_quests
CREATE TABLE IF NOT EXISTS eduai_quests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    narrative VARCHAR(2000),
    objective_type VARCHAR(255),
    objective_id BIGINT,
    reward_xp INTEGER DEFAULT 0,
    is_completed BOOLEAN DEFAULT false,
    created_at TIMESTAMP,
    completed_at TIMESTAMP,
    CONSTRAINT fk_eduai_quests_user FOREIGN KEY (user_id) REFERENCES app_users(id)
);

-- 11. gamification_config
CREATE TABLE IF NOT EXISTS gamification_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT,
    enabled BOOLEAN NOT NULL DEFAULT false,
    leaderboards_enabled BOOLEAN DEFAULT true,
    achievements_enabled BOOLEAN DEFAULT true,
    streaks_enabled BOOLEAN DEFAULT true,
    daily_challenges_enabled BOOLEAN DEFAULT true,
    xp_multiplier_max INTEGER DEFAULT 5,
    time_bonus_enabled BOOLEAN DEFAULT true,
    shop_enabled BOOLEAN DEFAULT false,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- 12. forum_reactions
CREATE TABLE IF NOT EXISTS forum_reactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT,
    user_id BIGINT,
    type VARCHAR(255),
    CONSTRAINT fk_forum_reactions_user FOREIGN KEY (user_id) REFERENCES app_users(id)
);

-- Add FK for forum_reactions.post_id only if forum_posts table exists
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'forum_posts') THEN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_forum_reactions_post') THEN
            ALTER TABLE forum_reactions ADD CONSTRAINT fk_forum_reactions_post FOREIGN KEY (post_id) REFERENCES forum_posts(id);
        END IF;
    END IF;
END $$;
