-- COMPREHENSIVE: Add ALL remaining missing columns, tables, and join tables

-- 1. calendar_events: missing is_unmanned
ALTER TABLE calendar_events ADD COLUMN IF NOT EXISTS is_unmanned BOOLEAN DEFAULT false;

-- 2. support_tickets: entire table missing
CREATE TABLE IF NOT EXISTS support_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    user_name VARCHAR(255),
    category VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    context_url VARCHAR(255),
    status VARCHAR(50) DEFAULT 'OPEN',
    severity VARCHAR(50) DEFAULT 'MEDIUM',
    admin_response TEXT,
    created_at TIMESTAMP,
    resolved_at TIMESTAMP,
    CONSTRAINT fk_support_tickets_user FOREIGN KEY (user_id) REFERENCES app_users(id)
);

-- 3. notifications: missing columns
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS related_entity_id BIGINT;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS related_entity_type VARCHAR(255);
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS action_url VARCHAR(255);

-- 4. courses: missing tags
ALTER TABLE courses ADD COLUMN IF NOT EXISTS tags TEXT;

-- 5. lesson: missing source_community_item_id
ALTER TABLE lesson ADD COLUMN IF NOT EXISTS source_community_item_id VARCHAR(255);

-- 6. assignment: missing gamification columns
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'assignment') THEN
        ALTER TABLE assignment ADD COLUMN IF NOT EXISTS xp_reward INTEGER DEFAULT 100;
        ALTER TABLE assignment ADD COLUMN IF NOT EXISTS xp_multiplier DOUBLE PRECISION DEFAULT 1.0;
        ALTER TABLE assignment ADD COLUMN IF NOT EXISTS time_bonus_minutes INTEGER;
        ALTER TABLE assignment ADD COLUMN IF NOT EXISTS time_bonus_xp INTEGER;
        ALTER TABLE assignment ADD COLUMN IF NOT EXISTS show_on_leaderboard BOOLEAN DEFAULT false;
        ALTER TABLE assignment ADD COLUMN IF NOT EXISTS achievement_id BIGINT;
        ALTER TABLE assignment ADD COLUMN IF NOT EXISTS source_community_item_id VARCHAR(255);
    END IF;
END $$;

-- 7. quizzes: missing source_community_item_id
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'quizzes') THEN
        ALTER TABLE quizzes ADD COLUMN IF NOT EXISTS source_community_item_id VARCHAR(255);
    END IF;
END $$;

-- 8. app_users: active_minutes type mismatch (V2 created as INTEGER, entity uses Long/BIGINT)
-- Safe to skip if already exists from V2

-- 9. lti_platforms: missing tenant_id
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'lti_platforms') THEN
        ALTER TABLE lti_platforms ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(255);
    END IF;
END $$;

-- 10. class_groups: missing mentor_id, main_teacher_id
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'class_groups') THEN
        ALTER TABLE class_groups ADD COLUMN IF NOT EXISTS mentor_id BIGINT;
        ALTER TABLE class_groups ADD COLUMN IF NOT EXISTS main_teacher_id BIGINT;
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_class_groups_mentor') THEN
            ALTER TABLE class_groups ADD CONSTRAINT fk_class_groups_mentor FOREIGN KEY (mentor_id) REFERENCES app_users(id);
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_class_groups_main_teacher') THEN
            ALTER TABLE class_groups ADD CONSTRAINT fk_class_groups_main_teacher FOREIGN KEY (main_teacher_id) REFERENCES app_users(id);
        END IF;
    END IF;
END $$;

-- 11. class_group_teachers: join table
CREATE TABLE IF NOT EXISTS class_group_teachers (
    class_group_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (class_group_id, user_id)
);
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_cgt_class_group') THEN
        ALTER TABLE class_group_teachers ADD CONSTRAINT fk_cgt_class_group FOREIGN KEY (class_group_id) REFERENCES class_groups(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_cgt_user') THEN
        ALTER TABLE class_group_teachers ADD CONSTRAINT fk_cgt_user FOREIGN KEY (user_id) REFERENCES app_users(id);
    END IF;
END $$;

-- 12. edugame_profiles: missing forum_activity_points
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'edugame_profiles') THEN
        ALTER TABLE edugame_profiles ADD COLUMN IF NOT EXISTS forum_activity_points INTEGER DEFAULT 0;
    END IF;
END $$;
