-- Skills Gap Analysis Tables
CREATE TABLE IF NOT EXISTS skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    category VARCHAR(255),
    description TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS course_skill_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    skill_id BIGINT NOT NULL REFERENCES skills(id) ON DELETE CASCADE,
    contribution_weight DOUBLE PRECISION DEFAULT 1.0, -- Points/Weight this course gives to the skill
    required_level DOUBLE PRECISION DEFAULT 100.0,   -- Target level for this skill in this course context
    UNIQUE (course_id, skill_id)
);

CREATE TABLE IF NOT EXISTS student_skill_levels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
    skill_id BIGINT NOT NULL REFERENCES skills(id) ON DELETE CASCADE,
    current_level DOUBLE PRECISION DEFAULT 0.0,
    last_updated TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (student_id, skill_id)
);

-- Initial Skills (Examples)
INSERT INTO skills (name, category, description) VALUES 
('Problemlösning', 'General', 'Förmågan att analysera och lösa komplexa problem.'),
('Teknisk Dokumentation', 'Communication', 'Skriva tydlig och strukturerad teknisk dokumentation.'),
('Kritiskt Tänkande', 'General', 'Analysera information objektivt och dra välgrundade slutsatser.'),
('React Hooks', 'Frontend', 'Djup förståelse för state och side-effects i React.'),
('Database Design', 'Backend', 'Förmåga att designa skalbara och normaliserade databasscheman.');

-- Index for performance
CREATE INDEX IF NOT EXISTS idx_student_skill_user ON student_skill_levels(student_id);
CREATE INDEX IF NOT EXISTS idx_course_skill_course ON course_skill_mapping(course_id);
