-- Ensure Adaptive Learning tables exist in the public schema
-- Some environments or configurations may expect these in public even in multi-tenant mode

CREATE TABLE IF NOT EXISTS public.adaptive_learning_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT UNIQUE NOT NULL REFERENCES public.app_users(id),
    visual_score INTEGER DEFAULT 50,
    auditory_score INTEGER DEFAULT 50,
    kinesthetic_score INTEGER DEFAULT 50,
    pace_preference VARCHAR(20) DEFAULT 'MODERATE',
    struggle_areas TEXT,
    strength_areas TEXT,
    last_analyzed TIMESTAMP,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.adaptive_recommendations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.app_users(id),
    title VARCHAR(255) NOT NULL,
    description TEXT,
    type VARCHAR(50) NOT NULL,
    ai_reasoning TEXT,
    reasoning_trace TEXT,
    status VARCHAR(50) DEFAULT 'NEW',
    priority_score INTEGER DEFAULT 50,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Index for performance
CREATE INDEX IF NOT EXISTS idx_arp_user ON public.adaptive_learning_profiles(user_id);
CREATE INDEX IF NOT EXISTS idx_arc_user ON public.adaptive_recommendations(user_id);
