-- Migration to create missing flashcard tables
CREATE TABLE IF NOT EXISTS flashcard_decks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    user_id BIGINT,
    course_id BIGINT,
    total_cards INTEGER DEFAULT 0,
    cards_due INTEGER DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_studied_at TIMESTAMP,
    CONSTRAINT fk_flashcard_deck_user FOREIGN KEY (user_id) REFERENCES app_users(id) ON DELETE CASCADE,
    CONSTRAINT fk_flashcard_deck_course FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS flashcards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deck_id BIGINT,
    front VARCHAR(2000),
    back VARCHAR(2000),
    difficulty VARCHAR(255),
    ease_factor DOUBLE PRECISION DEFAULT 2.5,
    interval_days INTEGER DEFAULT 0,
    repetitions INTEGER DEFAULT 0,
    next_review TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_reviewed TIMESTAMP,
    is_learned BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_flashcard_deck FOREIGN KEY (deck_id) REFERENCES flashcard_decks(id) ON DELETE CASCADE
);
