-- Spaced Repetition Progress
CREATE TABLE user_flashcard_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    flashcard_id BIGINT NOT NULL,
    ease_factor DOUBLE PRECISION DEFAULT 2.5,
    interval_days INTEGER DEFAULT 0,
    repetitions INTEGER DEFAULT 0,
    next_review TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_reviewed TIMESTAMP(6),
    is_learned BOOLEAN DEFAULT FALSE,
    UNIQUE(user_id, flashcard_id),
    CONSTRAINT fk_flashcard_progress_user FOREIGN KEY (user_id) REFERENCES app_users(id) ON DELETE CASCADE,
    CONSTRAINT fk_flashcard_progress_card FOREIGN KEY (flashcard_id) REFERENCES flashcards(id) ON DELETE CASCADE
);

-- AI Coach Recommendations
CREATE TABLE coach_recommendations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL, -- e.g. "DAILY_TIP", "NEXT_ACTION", "ENCOURAGEMENT"
    content TEXT NOT NULL,
    action_url VARCHAR(255),
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP(6),
    CONSTRAINT fk_coach_rec_user FOREIGN KEY (user_id) REFERENCES app_users(id) ON DELETE CASCADE
);
