CREATE TABLE IF NOT EXISTS spaced_repetition_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    content TEXT,
    category VARCHAR(255) NOT NULL,
    source_id BIGINT,
    repetitions INTEGER DEFAULT 0,
    easiness_factor DOUBLE PRECISION DEFAULT 2.5,
    interval INTEGER DEFAULT 0,
    last_reviewed TIMESTAMP,
    next_review_date TIMESTAMP,
    created_at TIMESTAMP,
    CONSTRAINT fk_spaced_rep_user FOREIGN KEY (user_id) REFERENCES app_users(id)
);
