-- Migration to create exam_integrity_events table
CREATE TABLE IF NOT EXISTS exam_integrity_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id BIGINT,
    student_id BIGINT,
    event_type VARCHAR(255),
    timestamp TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    details VARCHAR(1000)
);

-- Add constraints (Optional but good for data integrity)
-- ALTER TABLE IF EXISTS exam_integrity_events ADD CONSTRAINT FK_integrity_quiz FOREIGN KEY (quiz_id) REFERENCES quizzes(id);
-- ALTER TABLE IF EXISTS exam_integrity_events ADD CONSTRAINT FK_integrity_student FOREIGN KEY (student_id) REFERENCES app_users(id);

CREATE INDEX idx_integrity_quiz ON exam_integrity_events(quiz_id);
CREATE INDEX idx_integrity_student ON exam_integrity_events(student_id);
